[package]
name = "n1proxy_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
libc = "0.2.147"
sha2 = "0.10.7"
rsa = { version = "0.9.2", features = ["sha2"] }
rand = "0.8.5"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
aes = "0.8.3"
cbc = "0.1.2"

# [profile.release]
# opt-level = 3
# lto = true
# codegen-units = 1
# panic = 'abort'
